### ISSUE TITLE
Comparison to max-pooling

### ISSUE THREAD

**Issue by mys007** [achaman2/truly_shift_invariant_cnns#3]
Hi, interesting work! I was wondering what is the main difference of APS to simple max-pooling (resp. un-max-pooling for your follow-up paper): I guess max pooling is a special case of APS for single-channel tensors? So is the main point of your work that one can extend this concept to multi-channel tensors by choosing the pooling index based on the pixel norm over all channels? Thanks a lot!

**Comment by achaman2** [comment]
Hello. Max-pooling and APS are actually very different operations.

Strided max-pooling divides a signal (or tensor) into a bunch of non-overlapping windows and returns the maximum intensity pixel from each. This is a very local operation since pixel selection in each window has nothing to do with the intensities in the other regions of the signal. 

APS, on the other hand, considers different polyphase components of a signal—for eg. x(2n) and x(2n+1) for a 1-D signal x(n)—and returns the component with the highest norm as the downsampled output. 

By selecting the sampling grid in this global fashion, APS obtains a downsampled output that is consistent to shifts, which  is not the case with max-pooling.

Max-unpooling and APS-U from the followup paper can be compared in a similar manner.

I hope this answers your question! :)

**Comment by mys007** [comment]
Thanks for the fast response and clarification! I understand now, a clever idea. I have re-read your paper and it's actually clearly written there as well, sorry for skimming it too fast earlier.

**Comment by achaman2** [comment]
Thank you and no problem at all!
