### ISSUE TITLE
Perfect shift-invariance with APS (not 100% consistency)

### ISSUE THREAD

**Issue by DuyguSerbes** [achaman2/truly_shift_invariant_cnns#5]
Hello,

I really appreciate your work! 

When I run your repo, unfortunately, I cannot receive 100% percent consistency. In the paper, figure 5 shows that I should get 100% percent consistency even at epoch 0. Could you please share the configuration I should run to get this result? 

Thanks in advance.

**Comment by achaman2** [comment]
Hello! 

How did you generate shifts in the input? If you circularly shift the cifar-10 images and use circular padding in the neural network (the default implementation in the repo), it should result in 100% consistency.

Please let me know if you still experience any difficulties!

**Comment by NTT123** [comment]
Hi @achaman2, thank you for publishing the code!

If I understand correctly, the 100% shift-invariance guarantee very much depends on the fact that the shifted input picture is circular padded. However, I think this assumption does not cover shifted images in the real world.

Consider a large picture and we take two nearby crops of that picture. These two cropped pictures are only different at the edges. However, they will have very different internal activations using APS (without blurring).

I'm guessing that the benefits of shift-invariance is due to blurring, instead.

**Comment by achaman2** [comment]
Hi,

100% shift invariance on all input images is never possible when shifts are generated using cropping. Because, as you rightly pointed, the 2 images would have different pixel content near the edges. 

Robustness to shifts (measured using classification consistency in this work) generated using crops can however still be improved using APS. This is because loss of shift invariance happens due to both downsampling and boundary artifacts. Unlike other approaches, APS solves the problem caused by downsampling completely. 

When you consider boundary effects caused by cropping, these differences are only located near the boundaries in the earlier layers of the network and tend to not be large enough to impact norm maximization in those layers. APS, therefore, still helps there. 

We also empirically verify this in Table 3 in the paper. Combining APS and anti-aliasing always improves consistency over the case which uses anti-aliasing alone.

**Comment by NTT123** [comment]
Hi, thank you for your response! I didn't notice Table 3 in the paper, which indeed shows improvement over blurring.
